# Generated by Django 2.2.2 on 2019-06-28 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=6)),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
