# Generated by Django 2.2.2 on 2019-06-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friend',
        ),
    ]
