# Generated by Django 2.2.1 on 2019-06-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genere', models.CharField(max_length=255)),
                ('music_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
